# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:/home/vsts/work/1/s/flutter/bin"
    echo "printing the path of the flutter"
    echo $PATH
    # $FLUTTER_PATH --version
    # $FLUTTER_PATH pub get
    # $FLUTTER_PATH build apk
    # flutter config --no-analytics
    # flutter precache
  displayName: 'Install Flutter SDK'

- script: flutter --version
  displayName: 'Verify Flutter Installation'

- script: flutter pub get
  displayName: 'Get Flutter Dependencies'

- script: flutter build apk
  displayName: 'Build Android APK'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/build/app/outputs/flutter-apk'
    artifactName: 'android-apk'
  displayName: 'Publish Android APK Artifact'
