# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt update
    sudo apt install -y curl git unzip
    git clone https://github.com/flutter/flutter.git -b stable
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter --version
  displayName: 'Install Flutter SDK'

- script: flutter --version
  displayName: 'Verify Flutter Installation'

- script: flutter pub get
  displayName: 'Get Flutter Dependencies'

- script: flutter build apk
  displayName: 'Build Android APK'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/build/app/outputs/flutter-apk'
    artifactName: 'android-apk'
  displayName: 'Publish Android APK Artifact'
